/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import java.awt.Color;
import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import utils.DBConnection;


/**
 *
 * @author Others
 */
public class Audi extends javax.swing.JFrame {
    static int no;
    static int sid;
    Color bg;
    static ArrayList <JToggleButton> btns = new ArrayList <JToggleButton>();
    
    /**
     * Creates new form Audi
     */
    public Audi(int show_id) {
        this.sid=show_id;
        this.no=0;
        initComponents();
        bg = A1.getBackground();
        btns.add(0,A1);
        btns.add(1,A2);
        btns.add(2,A3);
        btns.add(3,A4);
        btns.add(4,A5);
        btns.add(5,B1);
        btns.add(6,B2);
        btns.add(7,B3);
        btns.add(8,B4);
        btns.add(9,B5);
        
        try{
                DBConnection connect = new DBConnection();
                Connection conn = connect.createConnection();
                Statement stmt = conn.createStatement();
                 ResultSet rs = stmt.executeQuery("select seat_ID from seats where Reserved is NOT NULL and Show_ID="+sid);
                 while(rs.next()){
                 if(rs.getString(1).equals("A1")) btns.get(0).setEnabled(false);
                 if(rs.getString(1).equals("A2")) btns.get(1).setEnabled(false);
                 if(rs.getString(1).equals("A3")) btns.get(2).setEnabled(false);
                 if(rs.getString(1).equals("A4")) btns.get(3).setEnabled(false);
                 if(rs.getString(1).equals("A5")) btns.get(4).setEnabled(false);
                 if(rs.getString(1).equals("B1")) btns.get(5).setEnabled(false);
                 if(rs.getString(1).equals("B2")) btns.get(6).setEnabled(false);
                 if(rs.getString(1).equals("B3")) btns.get(7).setEnabled(false);
                 if(rs.getString(1).equals("B4")) btns.get(8).setEnabled(false);
                 if(rs.getString(1).equals("B5")) btns.get(9).setEnabled(false);
                 }
                 if (!A1.isEnabled() && !A2.isEnabled() && !A3.isEnabled() && !A4.isEnabled() && !A5.isEnabled() && !B1.isEnabled() && !B2.isEnabled() && !B3.isEnabled() && !B4.isEnabled() && !B5.isEnabled()){
                 Book.setEnabled(false);
                 }
                
        } catch(SQLException e) {
            System.err.println(e);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        A2 = new javax.swing.JToggleButton();
        A1 = new javax.swing.JToggleButton();
        A3 = new javax.swing.JToggleButton();
        A5 = new javax.swing.JToggleButton();
        A4 = new javax.swing.JToggleButton();
        B2 = new javax.swing.JToggleButton();
        B1 = new javax.swing.JToggleButton();
        B3 = new javax.swing.JToggleButton();
        B5 = new javax.swing.JToggleButton();
        B4 = new javax.swing.JToggleButton();
        Book = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCREEN THIS WAY");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        A2.setText("A2");
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });

        A1.setText("A1");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });

        A3.setText("A3");
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });

        A5.setText("A5");
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });

        A4.setText("A4");
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });

        B2.setText("B2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B1.setText("B1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B3.setText("B3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B5.setText("B5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B4.setText("B4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        Book.setText("Book");
        Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("SubTotal:"+this.no);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Book, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(256, 256, 256)
                                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(208, 208, 208)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A2)
                    .addComponent(A3)
                    .addComponent(A1)
                    .addComponent(A4)
                    .addComponent(A5))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B2)
                    .addComponent(B3)
                    .addComponent(B1)
                    .addComponent(B4)
                    .addComponent(B5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Book, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed

        if(A2.isSelected()){
    this.no++;
    jLabel2.setText("SubTotal:"+this.no*100);
    A2.setBackground(Color.green);
        }
        else {
    this.no--;
    jLabel2.setText("SubTotal:"+this.no*100);
    A2.setBackground(bg);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_A2ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed

        if(B2.isSelected()){
    this.no++;
    jLabel2.setText("SubTotal:"+this.no*100);
    B2.setBackground(Color.green);
        }
        else {
    this.no--;
    jLabel2.setText("SubTotal:"+this.no*100);
    B2.setBackground(bg);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                        new Shows().setVisible(true);
                        dispose();
                           

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed

        if(A3.isSelected()){
    this.no++;
    jLabel2.setText("SubTotal:"+this.no*100);
    A3.setBackground(Color.green);
        }
        else {
    this.no--;
    jLabel2.setText("SubTotal:"+this.no*100);
    A3.setBackground(bg);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed

        if(A1.isSelected()){
     A1.setBackground(Color.green);
    this.no++;
    jLabel2.setText("SubTotal:"+this.no*100);
        }
        else {
    this.no--;
    A1.setBackground(bg);
      jLabel2.setText("SubTotal:"+this.no*100);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_A1ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed

        if(A4.isSelected()){
    this.no++;
    jLabel2.setText("SubTotal:"+this.no*100);
    A4.setBackground(Color.green);
        }
        else {
    this.no--;
    jLabel2.setText("SubTotal:"+this.no*100);
    A4.setBackground(bg);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_A4ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed

        if(A5.isSelected()){
    this.no++;
    jLabel2.setText("SubTotal:"+this.no*100);
    A5.setBackground(Color.green);
        }
        else {
    this.no--;
    jLabel2.setText("SubTotal:"+this.no*100);
    A5.setBackground(bg);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_A5ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed

        if(B1.isSelected()){
    this.no++;
    jLabel2.setText("SubTotal:"+this.no*100);
    B1.setBackground(Color.green);
        }
        else {
    this.no--;
    jLabel2.setText("SubTotal:"+this.no*100);
    B1.setBackground(bg);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed

        if(B3.isSelected()){
    this.no++;
    jLabel2.setText("SubTotal:"+this.no*100);
     B3.setBackground(Color.green);
        }
        else {
    this.no--;
    jLabel2.setText("SubTotal:"+this.no*100);
     B3.setBackground(bg);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed

        if(B4.isSelected()){
    this.no++;
    jLabel2.setText("SubTotal:"+this.no*100);
     B4.setBackground(Color.green);
        }
        else {
    this.no--;
    jLabel2.setText("SubTotal:"+this.no*100);
     B4.setBackground(bg);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed

        if(B5.isSelected()){
    this.no++;
    jLabel2.setText("SubTotal:"+this.no*100);
     B5.setBackground(Color.green);
        }
        else {
    this.no--;
    jLabel2.setText("SubTotal:"+this.no*100);
     B5.setBackground(bg);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_B5ActionPerformed

    private void BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookActionPerformed

  if (!A1.isSelected() && !A2.isSelected() && !A3.isSelected() && !A4.isSelected() && !A5.isSelected() && !B1.isSelected() && !B2.isSelected() && !B3.isSelected() && !B4.isSelected() && !B5.isSelected()){
   JOptionPane.showMessageDialog(this,"Please select a seat to book");
   return;
  }
            
     try {
            DBConnection connect = new DBConnection();
            Connection conn = connect.createConnection();
            Statement stmt = conn.createStatement();
          for(int i=0; i<5; i++){
          if(btns.get(i).isSelected()){
         stmt.executeUpdate("update Seats set Reserved ='"+Login.usrnm+"' where Seat_ID like 'A"+(i+1)+"' and Show_ID="+sid);
          } 
            }
          for(int i=5; i<10; i++){
           if(btns.get(i).isSelected()){              
              stmt.executeUpdate("update Seats set Reserved ='"+Login.usrnm+"' where Seat_ID like 'B"+(i-4)+"' and Show_ID="+sid);
           } 
             }
        } catch (SQLException e) {
            System.err.println(e);
        }
    
      new Confirmation().setVisible(true);
      dispose();
     
     
    }//GEN-LAST:event_BookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Audi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Audi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Audi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Audi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Audi(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton A1;
    private javax.swing.JToggleButton A2;
    private javax.swing.JToggleButton A3;
    private javax.swing.JToggleButton A4;
    private javax.swing.JToggleButton A5;
    private javax.swing.JToggleButton B1;
    private javax.swing.JToggleButton B2;
    private javax.swing.JToggleButton B3;
    private javax.swing.JToggleButton B4;
    private javax.swing.JToggleButton B5;
    private javax.swing.JButton Book;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
